version: '3.8'

services:
  abusolih_bot:
    restart: always
    build: ./
    command: ./main
    depends_on:
      - redis
    environment:
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
